In [24]:
import pandas as pd
import numpy as np
import matplotlib
import os
from sklearn import tree
from sklearn import preprocessing
%matplotlib inline

path = '/Users/damien/Documents/Sinf/2eme_bis/2eme_quadri/QDA/project_Classification/BDD-performance.csv'

my_df = pd.read_csv(path, sep=';')

label_encoder = preprocessing.LabelEncoder()

# Convert Sex variable to numeric
encoded_sex = label_encoder.fit_transform(my_df["sex"])

# Initialize model
tree_model = tree.DecisionTreeClassifier()

# Train the model
tree_model.fit(X = pd.DataFrame(encoded_sex), 
               y = my_df["age"])

with open("tree1.dot", 'w') as f:
     f = tree.export_graphviz(tree_model, 
                              feature_names=["sex"], 
                              out_file=f)

In [25]:
        from IPython.display import Image
Image("tree1.png") 

preds = tree_model.predict_proba(X = pd.DataFrame(encoded_sex))

pd.crosstab(preds[:,0], my_df["sex"])

sex         F    M
row_0
0.182692  208    0
0.235294    0  187

In [26]:
# Make data frame of predictors
predictors = pd.DataFrame([encoded_sex, my_df["traveltime"]]).T

# Train the model
tree_model.fit(X = predictors, 
               y = my_df["sex"])

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [27]:
with open("tree2.dot", 'w') as f:
     f = tree.export_graphviz(tree_model, 
                              feature_names=["Sex", "Class"], 
                              out_file=f)

In [43]:
# Get survival probability
preds = tree_model.predict_proba(X = predictors)

# Create a table of predictions by sex and class
pd.crosstab(preds[:,0], columns = [my_df["paid"], my_df["romantic"],my_df["age"], my_df["higher"], my_df["schoolsup"],my_df["failures"], my_df["goout"]])

paid       no                             ... yes                             \
romantic   no                             ... yes
age        15                             ...  17 18                   19
higher    yes                             ... yes no yes              yes
schoolsup  no                   yes       ... yes no  no          yes  no
failures    0           1  3      0       ...   0  0   0            0   1
goout       1  2  3  4  5  2  5   1  2  3 ...   4  3   2  3  4  5   2   2  4
row_0                                     ...
0.0         2  3  8  1  1  0  1   1  2  0 ...   0  1   3  0  0  2   1   0  1
1.0         1  4  2  0  0  1  0   0  0  1 ...   1  0   2  4  2  2   0   1  1

paid
romantic
age        20
higher    yes
schoolsup  no
failures    2
goout       3
row_0
0.0         0
1.0         1

[2 rows x 165 columns]